# Welcome to EMS Documents
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Administrator
email: admin@evostream.com
description: > # this means to ignore newlines until "baseurl:"
  EvoStream Media Server (EMS) documents are posted here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evostream.github.io" # the base hostname & protocol for your site
twitter_username: evostream
github_username:  evostream

# Build settings
markdown: kramdown
